### PR TITLE
[Test] Verify gfid self heal

### PR DESCRIPTION
**Pull request by leelavg**
Test: test_gfid_heal_from_shd
Steps:
- Create and mount a volume
- Set `self-heal-daemon` to `off`, cyclic brick down and perform gfid
operations
- Set `self-heal-daemon` to `on` and wait for heal completion
- Validate areequal checksum on backend bricks

Test: test_file_type_differs_heal_from_shd
Steps:
- Create and mount a volume
- Set `self-heal-daemon` to `off`, cyclic brick down and perform gfid
opertions differing in file types
- Set `self-heal-daemon` to `on` and wait for heal completion
- Validate areequal checksum on backend bricks

Test: test_sym_link_heal_from_shd
Steps:
- Create, mount and run IO on volume
- Set `self-heal-daemon` to `off`, cyclic brick down and perform
symlink operations
- Set `self-heal-daemon` to `on` and wait for heal completion
- Validate areequal checksum on backend bricks

Change-Id: I8418914d04f29200bab37eb6cca745dedf6fafd2
Signed-off-by: Leela Venkaiah G <lgangava@redhat.com>

### CODE REVIEW

**Comment by leelavg** [comment]
@aloganat @kshithijiyer @pranavprakash20 @karthik-us @BarakSason @srijan-sivakumar please review.

**Review by balakreddy — APPROVED** [review]
LGTM

**Review by kshithijiyer — APPROVED** [review]
LGTM Please upload successful run output to the PR

**Comment by leelavg** [comment]
- Pylint check
```
# pyc tests/functional/arbiter/test_verify_metadata_and_data_heal.py                       

           Sorting imports by 'isort'

           Running through 'yapf'

           Remove unused vars/imports by 'autoflake'

           Checking against 'flake8'

           Errors from 'pylint'

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```

- Run result from CentOS 8 with Replicated Volume + Glusterfs Mount
```
tests/functional/arbiter/test_verify_metadata_and_data_heal.py::TestSelfHeal_cplex_replicated_glusterfs::test_data_heal_from_shd PASSED
tests/functional/arbiter/test_verify_metadata_and_data_heal.py::TestSelfHeal_cplex_replicated_glusterfs::test_file_type_differs_heal_from_shd PASSED
tests/functional/arbiter/test_verify_metadata_and_data_heal.py::TestSelfHeal_cplex_replicated_glusterfs::test_gfid_heal_from_shd PASSED
tests/functional/arbiter/test_verify_metadata_and_data_heal.py::TestSelfHeal_cplex_replicated_glusterfs::test_metadata_heal_from_heal_cmd PASSED
tests/functional/arbiter/test_verify_metadata_and_data_heal.py::TestSelfHeal_cplex_replicated_glusterfs::test_metadata_heal_from_shd PASSED
tests/functional/arbiter/test_verify_metadata_and_data_heal.py::TestSelfHeal_cplex_replicated_glusterfs::test_sym_link_heal_from_shd PASSED

====================== 6 passed, 1362 warnings in 696.80s (0:11:36) =======================
```

- Run result from CentOS 7 with Arbiter Volume + Glusterfs Mount

```
tests/functional/arbiter/test_verify_metadata_and_data_heal.py::TestSelfHeal_cplex_arbiter_glusterfs::test_data_heal_from_shd PASSED
tests/functional/arbiter/test_verify_metadata_and_data_heal.py::TestSelfHeal_cplex_arbiter_glusterfs::test_file_type_differs_heal_from_shd PASSED
tests/functional/arbiter/test_verify_metadata_and_data_heal.py::TestSelfHeal_cplex_arbiter_glusterfs::test_gfid_heal_from_shd PASSED
tests/functional/arbiter/test_verify_metadata_and_data_heal.py::TestSelfHeal_cplex_arbiter_glusterfs::test_metadata_heal_from_heal_cmd PASSED
tests/functional/arbiter/test_verify_metadata_and_data_heal.py::TestSelfHeal_cplex_arbiter_glusterfs::test_metadata_heal_from_shd PASSED
tests/functional/arbiter/test_verify_metadata_and_data_heal.py::TestSelfHeal_cplex_arbiter_glusterfs::test_sym_link_heal_from_shd PASSED

============================================= 6 passed in 866.57 seconds =============================================
```

**Review by aloganat — APPROVED** [review]
LGTM

**Review by srijan-sivakumar — APPROVED** [review]

**Pull request merged**
