### PR TITLE
[TestFix] Fix AFR Failing tests

### PR DESCRIPTION
**Pull request by leelavg**
Change-Id: Ic0c156da244c3c4543547c513504f05627388ada
Signed-off-by: Leela Venkaiah G <lgangava@redhat.com>

### CODE REVIEW

**Comment by leelavg** [comment]
Verified below failing tests in CI, pasting here just for a reference

```
1. tests.functional.afr.test_split_brain_with_hard_link_file.TestSelfHeal_cplex_distributed-replicated_glusterfs.test_afr_heal_with_brickdown_hardlink - Fixed
2. tests.functional.afr.test_self_heal_with_full_algorithm.TestSelfHealWithFullAlgorithm_cplex_replicated_glusterfs.test_self_heal_with_full_algorithm - Fixed
3. tests.functional.afr.test_self_heal_with_full_algorithm.TestSelfHealWithFullAlgorithm_cplex_distributed-replicated_glusterfs.test_self_heal_with_full_algorithm - Fixed
4. tests.functional.afr.test_self_heal_with_full_algorithm.TestSelfHealWithFullAlgorithm_cplex_distributed-arbiter_glusterfs.test_self_heal_with_full_algorithm - Fixed
5. tests.functional.afr.test_self_heal_with_full_algorithm.TestSelfHealWithFullAlgorithm_cplex_arbiter_glusterfs.test_self_heal_with_full_algorithm - Fixed
6. tests.functional.afr.test_replace_brick_self_heal_io_in_progress.TestAFRSelfHeal_cplex_replicated_glusterfs.test_replace_brick_self_heal_io_in_progress - Fixed (arequal)
7. tests.functional.afr.test_replace_brick_self_heal_io_in_progress.TestAFRSelfHeal_cplex_distributed-replicated_glusterfs.test_replace_brick_self_heal_io_in_progress - Fixed (arequal)
8. tests.functional.afr.test_metadata_self_heal_client_side_heal.TestAFRMetaDataSelfHealClientSideHeal_cplex_replicated_glusterfs.test_metadata_self_heal_client_side_heal - Fixed (arequal)
9. tests.functional.afr.test_metadata_self_heal_client_side_heal.TestAFRMetaDataSelfHealClientSideHeal_cplex_distributed-replicated_glusterfs.test_metadata_self_heal_client_side_heal - Fixed (arequal)
10. tests.functional.afr.test_manual_heal_should_trigger_heal.TestSelfHeal_cplex_distributed_glusterfs.test_manual_heal_should_trigger_heal - Fixed (arequal)
11. tests.functional.afr.test_manual_heal_full_should_trigger_heal.TestSelfHeal_cplex_distributed_glusterfs.test_manual_heal_full_should_trigger_heal - Fixed (arequal)
12. tests.functional.afr.test_gfid_split_brain_resolution.TestSelfHeal_cplex_distributed-replicated_glusterfs.test_gfid_split_brain_resolution - Passing locally
13. tests.functional.afr.test_dist_to_repl_automatic_heal_should_be_triggered.TestSelfHeal_cplex_distributed_glusterfs.test_dist_to_repl_automatic_heal_should_be_triggered - Fixed (arequal)
14. tests.functional.afr.test_conservative_merge_of_files_heal_command.VerifySelfHealTriggersHealCommand_cplex_replicated_glusterfs.test_conservative_merge_of_files_heal_command - Fixed (arequal)
15. tests.functional.afr.test_client_side_quorum_with_fixed_for_cross3.ClientSideQuorumTestsWithSingleVolumeCross3_cplex_replicated_glusterfs.test_client_side_quorum_with_fixed_for_cross3 - Passing locally
16. tests.functional.afr.test_arb_to_repl_conversion_with_io.TestArbiterToReplicatedConversion_cplex_arbiter_glusterfs.test_arb_to_repl_conversion_with_io - Fixed
17. tests.functional.afr.test_afr_cli_no_splitbrain_resolution.TestSelfHeal_cplex_replicated_glusterfs.test_afr_gfid_heal - Passing locally
18. tests.functional.afr.heal.test_heal_info_no_hang.TestHealInfoNoHang_cplex_distributed-replicated_glusterfs.test_heal_info_no_hang - Fixed
```

**Comment by leelavg** [comment]
pls review @srijan-sivakumar (the arequal part)

**Comment by nik-redhat** [comment]
Hey, @leelavg now since the check for `anonymous inode` directory is being added, this [check](https://github.com/gluster/redant/pull/927/files#diff-8ddf8c6b9119819a967a585d182aa5d95eede23b811f46a14a52a4ada3d35653R491-R501) should also be added along with that, else it will throw an error for certain cases where the test does a checksum check on a directory inside the brick.

**Comment by leelavg** [comment]
hey @nik-redhat thanks for the review and explaining the corner case
- as discussed offline, i'm only interested in `stdout` of the command and just using that in the loop
- if `stdout` is empty then we are satisfying no `anon-inode` either in root of the brick or any subdir of the brick
- as current implementation is just enough for the use-case and being backward compatible, I'd like to proceed with current code without using extra conditionals.

**Review by nik-redhat — APPROVED** [review]
LGTM

**Review by srijan-sivakumar — APPROVED** [review]

**Review by pranavprakash20 — APPROVED** [review]
LGTM

**Review by aloganat — APPROVED** [review]

**Pull request merged**
