### PR TITLE
[LibFix] Fix cleanup error

### PR DESCRIPTION
**Pull request by srivickynesh**
Fix for issue #90 

Signed-off-by: Sri Vignesh <vigneshsri11@gmail.com>

### CODE REVIEW

**Review by pranavprakash20 — APPROVED** [review]
LGTM

**Review by kshithijiyer — APPROVED** [review]

**Comment by kshithijiyer** [comment]
@srivickynesh please run this with BVT and share the run results.

**Comment by srivickynesh** [comment]
Below test is ran using 4 node gluster setup:

tests/functional/bvt/test_basic.py::TestGlusterdSanity::test_glusterd_restart_stop_start PASSED
tests/functional/bvt/test_cvt.py::TestGlusterExpandVolumeSanity_cplex_distributed_glusterfs::test_expanding_volume_wh
en_io_in_progress PASSED
tests/functional/bvt/test_cvt.py::TestGlusterExpandVolumeSanity_cplex_replicated_glusterfs::test_expanding_volume_whe
n_io_in_progress PASSED
tests/functional/bvt/test_cvt.py::TestGlusterShrinkVolumeSanity_cplex_distributed-replicated_glusterfs::test_shrinking_volume_when_io_in_progress PASSED
tests/functional/bvt/test_cvt.py::TestGlusterShrinkVolumeSanity_cplex_distributed_glusterfs::test_shrinking_volume_when_io_in_progress PASSED
tests/functional/bvt/test_cvt.py::TestGlusterVolumeSetSanity_cplex_replicated_glusterfs::test_volume_set_when_io_in_progress PASSED
tests/functional/bvt/test_cvt.py::TestQuotaSanity_cplex_distributed-replicated_glusterfs::test_quota_enable_disable_enable_when_io_in_progress PASSED
tests/functional/bvt/test_cvt.py::TestQuotaSanity_cplex_distributed_glusterfs::test_quota_enable_disable_enable_when_io_in_progress PASSED
tests/functional/bvt/test_cvt.py::TestQuotaSanity_cplex_replicated_glusterfs::test_quota_enable_disable_enable_when_io_in_progress PASSED
tests/functional/bvt/test_cvt.py::TestSnapshotSanity_cplex_distributed-replicated_glusterfs::test_snapshot_basic_commands_when_io_in_progress PASSED
tests/functional/bvt/test_cvt.py::TestSnapshotSanity_cplex_distributed_glusterfs::test_snapshot_basic_commands_when_io_in_progress 
PASSED
tests/functional/bvt/test_cvt.py::TestGlusterReplaceBrickSanity_cplex_replicated_glusterfs::test_replace_brick_when_io_in_progress PASSED
tests/functional/bvt/test_cvt.py::TestGlusterReplaceBrickSanity_cplex_distributed-replicated_glusterfs::test_replace_brick_when_io_in_progress PASSED

**Review by balakreddy — APPROVED** [review]
LGTM

**Comment by aloganat** [comment]
LGTM

**Pull request merged**
