### PR TITLE
[LibFix] Remove getchildren from get_volume_list as deprecated

### PR DESCRIPTION
**Pull request by adityaramteke**
Signed-off-by: Aditya Ramteke <aramteke@redhat.com>

### CODE REVIEW

**Comment by pranavprakash20** [comment]
@adityaramteke As per my understanding, this patch includes changes just to `get_volume_list` and this has been tested and verified. There are many other places where `getchildren()` is used and since it requires proper testing to ensure that the change doesn't cause an issue to the existing tests, those will be send as a different patch, after proper testing. Please correct me if I go it wrong.

**Comment by adityaramteke** [comment]
@pranavprakash20, that's correct! I've added a different patch https://github.com/gluster/glusto-tests/pull/75 which includes all changes to remove `getchildren()` and will update after proper testing. Thanks!

**Review by balakreddy — APPROVED** [review]
lgtm

**Review by pranavprakash20 — APPROVED** [review]
LGTM

**Review by leelavg — APPROVED** [review]
LGTM

**Pull request merged**
